apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-resilience-platform
  labels:
    app: resilience-platform
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: resilience-platform
  template:
    metadata:
      labels:
        app: resilience-platform
    spec:
      containers:
        - name: platform
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
